--UPDATE [MAJOR_CAMPANA].[dbo].[PERSONA] SET [PROVINCIA]='' WHERE [PROVINCIA] IN ('0','A')
--UPDATE [MAJOR_CAMPANA].[dbo].[PERSONA] SET [PROVINCIA]='CIUDAD AUTÓNOMA BUENOS AIRES' WHERE [PROVINCIA]='Capital Federal'


  /*
  UPDATE PERSONA
  SET PROVINCIA='BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE '%CAMPANA' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='BUENOS AIRES'
  WHERE TRIM(LOCALIDAD)='OTAMENDI' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE '%RIO LUJAN%' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE '%CARDALES%' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE '%LOS PIONEROS%' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='CIUDAD AUTÓNOMA BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE 'CAPITAL%' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='CIUDAD AUTÓNOMA BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE 'BUENOS AIRES' AND (PROVINCIA='' OR PROVINCIA='0')

  UPDATE PERSONA
  SET PROVINCIA='BUENOS AIRES'
  WHERE TRIM(LOCALIDAD) LIKE 'ZARATE' AND (PROVINCIA='' OR PROVINCIA='0')
  */