--SELECT 'INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES ('||id::varchar||','''||codigo||''','''||tipo||''','''||nombre||''','||orden::varchar||');' FROM lista ORDER BY id ASC

TRUNCATE TABLE lista;

INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (500,'1','TipoPersona','Física',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (501,'2','TipoPersona','Jurídica',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (510,'1','TipoDocumento','D.N.I.',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (512,'3','TipoDocumento','L.E.',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (513,'4','TipoDocumento','L.C.',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (514,'5','TipoDocumento','Pasaporte',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (515,'6','TipoDocumento','C.U.I.T.',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (516,'7','TipoDocumento','Extranjeros',6);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (517,'9','TipoDocumento','Sin documento',7);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (518,'20','TipoDocumento','Organismos oficiales',8);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (520,'1','TipoContacto','Teléfono',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (522,'3','TipoContacto','Sitio web',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (524,'5','TipoContacto','Teléfono móvil',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (525,'6','TipoContacto','Correo electrónico',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (526,'7','TipoContacto','Otro',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (530,'1','TipoGeoreferencia','Open Street Map',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (531,'2','TipoGeoreferencia','Google Street View',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (532,'3','TipoGeoreferencia','API Local',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (533,'4','TipoGeoreferencia','Carga por zona',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (534,'5','TipoGeoreferencia','Carga manual',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (535,'6','TipoGeoreferencia','Carga directa',6);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (540,'CF','CondicionFiscal','Consumidor final',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (541,'EX','CondicionFiscal','Exento',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (542,'MO','CondicionFiscal','Monotributista',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (543,'RI','CondicionFiscal','Responsable inscripto',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (544,'ND','CondicionFiscal','No declarado',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (550,'1','IngresosBrutos','Gravado',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (551,'2','IngresosBrutos','Exento',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (560,'M','Genero','Masculino',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (561,'F','Genero','Femenino',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (562,'I','Genero','Indefinido',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (570,'1','EstadoCivil','Casado/a',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (571,'2','EstadoCivil','Soltero/a',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (572,'3','EstadoCivil','Separado/a',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (573,'4','EstadoCivil','Viudo/a',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (574,'5','EstadoCivil','Divorciado/a',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (575,'6','EstadoCivil','Concubinato',6);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (580,'1','NivelEstudio','Primaria',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (581,'2','NivelEstudio','Secundaria',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (582,'3','NivelEstudio','Terciaria',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (583,'4','NivelEstudio','Universitaria',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (590,'1','EntidadBancaria','Banco Nación',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (591,'2','EntidadBancaria','Banco Provincia',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (592,'3','EntidadBancaria','Banco Ciudad',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (593,'4','EntidadBancaria','Banco Galicia',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (610,'1','TipoMedioPago','Tarjeta de crédito/débito',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (611,'2','TipoMedioPago','CBU/CVU',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (620,'1','TipoTarjeta','Tarjeta de crédito',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (621,'2','TipoTarjeta','Tarjeta de débito',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (630,'1','MarcaTarjeta','Visa',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (631,'2','MarcaTarjeta','MasterCard',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (632,'3','MarcaTarjeta','American Express',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (650,'1','EstadoFirma','Pendiente',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (651,'2','EstadoFirma','Firmado',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (652,'3','EstadoFirma','Rechazado',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (660,'1','TipoFirma','Título ejecutivo',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (661,'2','TipoFirma','Certificado libre deuda automotor',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (662,'3','TipoFirma','Certificado baja automotor',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (663,'4','TipoFirma','Certificado de deuda inmueble',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (664,'5','TipoFirma','Certificado catastral',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2000,'1','TipoExpediente','Externo',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2001,'2','TipoExpediente','Interno',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2002,'3','TipoExpediente','Con característica',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2003,'4','TipoExpediente','Expediente civil',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2004,'5','TipoExpediente','Alcance',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2005,'6','TipoExpediente','Expediente D.O.P',6);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2006,'7','TipoExpediente','Carpeta de obra',7);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2100,'465100','RubroAfip','Venta al por mayor de equipos, periféricos, accesorios y programas informáticos',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2101,'465210','RubroAfip','Venta al por mayor de equipos de telefonía y comunicaciones',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2102,'465220','RubroAfip','Venta al por mayor de componentes electrónicos',3);
