USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE categoria_vehiculo

INSERT INTO categoria_vehiculo
SELECT
    ROW_NUMBER() OVER (ORDER BY COD_CATEGORIA_VEHICULO, COD_INCISO_VEHICULO) id,
    COD_CATEGORIA_VEHICULO codigo,
    Convert(varchar,COD_CATEGORIA_VEHICULO)+'-'+ISNULL(COD_INCISO_VEHICULO,'')+'-'+Convert(varchar,LIMITE_SUPERIOR) nombre,
    ROW_NUMBER() OVER (ORDER BY COD_CATEGORIA_VEHICULO, COD_INCISO_VEHICULO) orden,
    inc.ID id_inciso_vehiculo,
    LIMITE_INFERIOR,
    LIMITE_SUPERIOR,
    A.CODIGO_SUCERP
FROM MAJOR_CAMPANA.dbo.CATEGORIA_VEHICULO A
         left join LARAMIE_CAMPANA.dbo.inciso_vehiculo inc on inc.codigo=A.COD_INCISO_VEHICULO
ORDER BY id
GO
