-- Crear schemas para cada módulo
CREATE SCHEMA IF NOT EXISTS seguridad;
CREATE SCHEMA IF NOT EXISTS administracion;
CREATE SCHEMA IF NOT EXISTS auditoria;
CREATE SCHEMA IF NOT EXISTS comunicacion;
CREATE SCHEMA IF NOT EXISTS contaduria;
CREATE SCHEMA IF NOT EXISTS importacion;
CREATE SCHEMA IF NOT EXISTS ingresos_publicos;
CREATE SCHEMA IF NOT EXISTS interface;
CREATE SCHEMA IF NOT EXISTS tesoreria;
CREATE SCHEMA IF NOT EXISTS wav;

-- Extensiones útiles
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "unaccent";
