USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE ubicacion_comercio
GO

INSERT INTO ubicacion_comercio
SELECT
	Cast(COD_UBICACION_COMERCIO as int) id,
	Cast(COD_UBICACION_COMERCIO as int) codigo,
	NOMBRE nombre,
	ROW_NUMBER() OVER(ORDER BY Cast(COD_UBICACION_COMERCIO as int) ASC) orden,
	Cast(COEFICIENTE as real) coeficiente
FROM MAJOR_CAMPANA.dbo.UBICACION_COMERCIO
Where COD_UBICACION_COMERCIO != 0
ORDER BY Cast(COD_UBICACION_COMERCIO as int)
GO
