from .personas import router as personas_router
from .expedientes import router as expedientes_router
from .listas import router as listas_router
from .entidades import router as entidades_router
from .direcciones import router as direcciones_router
from .contactos import router as contactos_router
from .archivos import router as archivos_router
from .observaciones import router as observaciones_router
from .documentos import router as documentos_router
from .medios_pago import router as medios_pago_router
from .etiquetas import router as etiquetas_router
from .entidad_definiciones import router as entidad_definiciones_router
from .paises import router as paises_router
from .provincias import router as provincias_router
from .localidades import router as localidades_router
from .cuentas_contables import router as cuentas_contables_router
from .jurisdicciones import router as jurisdicciones_router
from .recursos_por_rubro import router as recursos_por_rubro_router
