USE LARAMIE_CAMPANA
GO

CREATE TABLE vehiculo (
	"id" bigint NOT NULL,
	id_cuenta bigint NULL,
	numero_cuenta varchar(50) NOT NULL,
	id_estado_carga bigint NOT NULL,
	fecha_carga_inicio datetime NOT NULL,
	fecha_carga_fin datetime NULL,
    dominio nvarchar(20) NOT NULL,
    dominio_anterior nvarchar(20) NOT NULL,
    anio_modelo nvarchar(50) NOT NULL,
    marca nvarchar(250) NOT NULL,
    codigo_marca nvarchar(250) NOT NULL,
    modelo nvarchar(250) NOT NULL,
    id_inciso_vehiculo bigint NULL,
    id_tipo_vehiculo bigint NULL,
    id_categoria_vehiculo bigint NULL,
    numero_motor nvarchar(250) NOT NULL,
    marca_motor nvarchar(250) NOT NULL,
    numero_chasis nvarchar(250) NOT NULL,
    serie_motor nvarchar(250) NOT NULL,
    legajo nvarchar(250) NOT NULL,
    valuacion numeric(18,2) NOT NULL,
    peso nvarchar(50) NOT NULL,
    carga nvarchar(50) NOT NULL,
    cilindrada nvarchar(50) NOT NULL,
    id_origen_fabricacion bigint NULL,
    id_combustible bigint NULL,
    id_uso_vehiculo bigint NULL,
    id_motivo_baja_vehiculo bigint NULL,
    recupero nvarchar(250) NOT NULL,
    radicacion_anterior nvarchar(250) NOT NULL,
    fecha_alta datetime,
    fecha_patentamiento datetime,
    fecha_radicacion datetime,
    fecha_transferencia datetime,
    fecha_compra datetime,
    fecha_baja datetime,
    fecha_habilitacion_desde datetime,
    fecha_habilitacion_hasta datetime,
    fecha_ddjj datetime,
	codigo_mtm nvarchar(50) NOT NULL
)
GO
