USE LARAMIE_CAMPANA
GO

SELECT 
	id,
	id_cuenta,
	id_estado_carga,
	fecha_carga_inicio,
	fecha_carga_fin,
	dominio,
	dominio_anterior,
	anio_modelo,
	marca,
	codigo_marca,
	modelo,
	id_inciso_vehiculo,
	id_tipo_vehiculo,
	id_categoria_vehiculo,
	numero_motor,
	marca_motor,
	numero_chasis,
	serie_motor,
	legajo,
	valuacion,
	peso,
	carga,
	cilindrada,
	id_origen_fabricacion,
	id_combustible,
	id_uso_vehiculo,
	id_motivo_baja_vehiculo,
	recupero,
	radicacion_anterior,
	fecha_alta,
	fecha_patentamiento,
	fecha_radicacion,
	fecha_transferencia,
	fecha_compra,
	fecha_baja,
	fecha_habilitacion_desde,
	fecha_habilitacion_hasta,
	fecha_ddjj,
	null id_firma_digital_libre_deuda,
	null id_estado_firma_libre_deuda,
	null id_firma_digital_baja,
	null id_estado_firma_baja,
	codigo_mtm
FROM vehiculo
ORDER BY id
GO