USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE tipo_construccion_funeraria
GO

INSERT INTO tipo_construccion_funeraria
SELECT
	(ROW_NUMBER() OVER (ORDER BY COD_TIPO_CONSTRUCCION_FUNERARIA)) id,
	COD_TIPO_CONSTRUCCION_FUNERARIA codigo,
	DESCRIPCION nombre,
	ROW_NUMBER() OVER(ORDER BY COD_TIPO_CONSTRUCCION_FUNERARIA) orden,
	(case when CON_VENCIMIENTO='S' then 1 else 0 end) con_vencimiento,
	PLAZO_MAX_CONCESION,
	TERMINO_CONCESION1,
	TERMINO_CONCESION2,
	PLAZO_MAX_RENOVACION,
	TERMINO_RENOVACION1,
	TERMINO_RENOVACION2,
	(case when TIENE_UBICACION='S' then 1 else 0 end) tiene_ubicacion,
	(case when TIENE_SUPERFICIE='S' then 1 else 0 end) tiene_superficie
FROM
	MAJOR_CAMPANA.dbo.TIPO_CONSTRUCCION_FUNERARIA
WHERE
	COD_TIPO_CONSTRUCCION_FUNERARIA > 0
GO
