USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE categoria_tasa
GO

INSERT INTO categoria_tasa
SELECT
	 ROW_NUMBER() OVER (ORDER BY COD_CATEGORIA_UBICACION) id
    ,COD_CATEGORIA_UBICACION codigo
	,NOMBRE nombre
	,ROW_NUMBER() OVER (ORDER BY COD_CATEGORIA_UBICACION) orden
	,(case when ES_PLAN='S' then 1 else 0 end) es_plan
	,(case when ES_DERECHO_ESPONTANEO='S' then 1 else 0 end) es_plan
FROM MAJOR_CAMPANA.dbo.CATEGORIA_TASA
WHERE COD_CATEGORIA_UBICACION <> 0
GO

