USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE tipo_anuncio
GO

INSERT INTO tipo_anuncio
SELECT 
	 (CASE WHEN COD_TIPO_ANUNCIO=0 THEN 9999 ELSE COD_TIPO_ANUNCIO END) id
    ,(CASE WHEN COD_TIPO_ANUNCIO=0 THEN 9999 ELSE COD_TIPO_ANUNCIO END) codigo
    ,NOMBRE nombre
    ,(ROW_NUMBER() OVER (ORDER BY COD_TIPO_ANUNCIO)) orden
    ,PORCENTAJE porcentaje
    ,IMPORTE importe
FROM MAJOR_CAMPANA.dbo.TIPO_ANUNCIO
ORDER BY id
GO
