USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE Pais
GO

INSERT INTO Pais
SELECT
	cast(COD_PAIS as bigint) id,
	COD_PAIS codigo,
	DESCRIPCION nombre,
	(ROW_NUMBER() OVER (ORDER BY COD_PAIS)) orden
FROM MAJOR_CAMPANA.dbo.PAIS
WHERE COD_PAIS<>0
ORDER BY COD_PAIS