import {
    HomeView,
    UnauthorizedView,
    VariablesView,
    VariablesGlobalesView,
    InmueblesView,
    InmuebleView,
    ComerciosView,
    ComercioView,
    VehiculosView,
    VehiculoView,
    CementeriosView,
    CementerioView,
    FondeaderosView,
    FondeaderoView,
    EspecialesView,
    EspecialView,
    EmisionDefinicionesView,
    EmisionDefinicionView,
    EmisionEjecucionesView,
    EmisionEjecucionView,
    TasasView,
    TasaView,
    SubTasasView,
    SubTasaView,
    CertificadosEscribanoView,
    PlantillasDocumentosView,
    TiposActosProcesalesView,
    OrganosJudicialesView,
    ControladoresView,
    ContribuyentesView,
    CertificadosApremiosView,
    CertificadoApremioView,
    CertificadoApremioItemsView,
    TipoRelacionesCertificadoApremioPersonaView,
    ApremiosView,
    ApremioView,
    CuentaCorrienteView,
    DeudaView,
    ConvenioDefinicionesView,
    PlanPagoView,
    PlanPagoDefinicionesView,
    PlanPagoDefinicionView,
    PagoACuentaView,
    PagoContadoView,
    PageNotFoundView,
    EntidadesView,
    EntidadView,
    PagoContadoDefinicionView,
    PagoContadoDefinicionesView,
    ProcedimientosView,
    ProcedimientoView,
    CuentasPruebaView,
    RecibosEspecialesView,
    ReciboEspecialView,
    PagoReciboEspecialView,
} from '../views';

export const PrivateRoutes = [
  {
    index: 0,
    code: "home",
    path: "/",
    component: HomeView,
    title: "Home",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 10,
    code: "unauthorized",
    path: "/unauthorized",
    component: UnauthorizedView,
    title: "Unauthorized",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
//Tributos
  {
    index: 11,
    path: "",
    component: null,
    title: "Tributos",
    showHeader: true,
    nivelMenu: 1,
    children: [20,30,40,50,60,70,72]
  },
  {
    index: 20,
    code: "inmueble_GET",
    path: "/inmuebles",
    component: InmueblesView,
    title: "Inmuebles",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 21,
    code: "inmueble_GET",
    path: ["/inmueble/:mode", "/inmueble/:mode/:id"],
    component: InmuebleView,
    title: "Inmueble",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 30,
    code: "comercio_GET",
    path: "/comercios",
    component: ComerciosView,
    title: "Comercios",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 31,
    code: "comercio_GET",
    path: ["/comercio/:mode", "/comercio/:mode/:id"],
    component: ComercioView,
    title: "Comercio",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 40,
    code: "vehiculo_GET",
    path: "/vehiculos",
    component: VehiculosView,
    title: "Vehículos",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 41,
    code: "vehiculo_GET",
    path: ["/vehiculo/:mode", "/vehiculo/:mode/:id"],
    component: VehiculoView,
    title: "Vehículo",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 50,
    code: "cementerio_GET",
    path: "/cementerios",
    component: CementeriosView,
    title: "Cementerios",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 51,
    code: "cementerio_GET",
    path: ["/cementerio/:mode", "/cementerio/:mode/:id"],
    component: CementerioView,
    title: "Cementerio",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 60,
    code: "fondeadero_GET",
    path: "/fondeaderos",
    component: FondeaderosView,
    title: "Fondeaderos",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 61,
    code: "fondeadero_GET",
    path: ["/fondeadero/:mode", "/fondeadero/:mode/:id"],
    component: FondeaderoView,
    title: "Fondeadero",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 70,
    code: "especial_GET",
    path: "/cuentas-especiales",
    component: EspecialesView,
    title: "Cuentas Especiales",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 71,
    code: "especial_GET",
    path: ["/cuenta-especial/:mode", "/cuenta-especial/:mode/:id"],
    component: EspecialView,
    title: "Cuenta Especial",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 72,
    code: "contribuyente_GET",
    path: "/contribuyentes",
    component: ContribuyentesView,
    title: "Contribuyentes",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 180,
    code: "cuenta-corriente_GET",
    path: "/cuenta-corriente/:filter/:mode/:id",
    component: CuentaCorrienteView,
    title: "Cuenta Corriente",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
  {
    index: 182,
    code: "deuda_GET",
    path: "/deuda/:mode/:id",
    component: DeudaView,
    title: "Deuda",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
  {
    index: 183,
    code: "plan-pago_GET",
    path: "/plan-pago/:processKey",
    component: PlanPagoView,
    title: "Planes de Pago",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
  {
    index: 184,
    code: "pago-contado_GET",
    path: "/pago-contado/:processKey",
    component: PagoContadoView,
    title: "Pago Contado",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
  {
    index: 185,
    code: "pago-acuenta_GET",
    path: "/pago-acuenta/:processKey",
    component: PagoACuentaView,
    title: "Pago a Cuenta",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
//Facturación
  {
    index: 80,
    path: "",
    component: null,
    title: "Facturación",
    showHeader: true,
    nivelMenu: 1,
    children: [81,85,87,89,240,242,232,233,235]
  },
  {
    index: 81,
    code: "procedimiento_GET",
    path: "/procedimientos",
    component: ProcedimientosView,
    title: "Procedimientos de Emisión",
    showHeader: true,
    nivelMenu: 2,
    children: [],
  },
  {
    index: 82,
    code: "procedimiento_GET",
    path: ["/procedimiento/:mode", "/procedimiento/:mode/:id"],
    component: ProcedimientoView,
    title: "Procedimientos de Emisión",
    showHeader: true,
    nivelMenu: 0,
    children: [],
  },
  {
    index: 85,
    code: "emision-definicion_GET",
    path: "/emision-definiciones",
    component: EmisionDefinicionesView,
    title: "Definición de Emisiones",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 86,
    code: "emision-definicion_GET",
    path: ["/emision-definicion/:mode", "/emision-definicion/:mode/:id"],
    component: EmisionDefinicionView,
    title: "Definición de Emisión",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 87,
    code: "emision-ejecucion_GET",
    path: "/emision-ejecuciones",
    component: EmisionEjecucionesView,
    title: "Ejecución de Emisiones",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 88,
    code: "emision-ejecucion_GET",
    path: ["/emision-ejecucion/:mode", "/emision-ejecucion/:mode/:id"],
    component: EmisionEjecucionView,
    title: "Ejecución de Emisión",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 89,
    code: "tipo-plan-pago_GET",
    path: "/convenio-definiciones",
    component: ConvenioDefinicionesView,
    title: "Definición de Convenios",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 240,
    code: "plan-pago-definicion_GET",
    path: "/planes-pago-definicion",
    component: PlanPagoDefinicionesView,
    title: "Definición de Planes de Pago",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 241,
    code: "plan-pago-definicion_GET",
    path: ["/plan-pago-definicion/:mode", "/plan-pago-definicion/:mode/:id"],
    component: PlanPagoDefinicionView,
    title: "Definición de Plan de Pago",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 242,
    code: "pago-contado-definicion_GET",
    path: "/pagos-contados-definicion",
    component: PagoContadoDefinicionesView,
    title: "Definición de Pagos Contados",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 243,
    code: "pago-contado-definicion_GET",
    path: ["/pago-contado-definicion/:mode", "/pago-contado-definicion/:mode/:id"],
    component: PagoContadoDefinicionView,
    title: "Definición de Pago Contado",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 233,
    code: "recibo-especial_GET",
    path: "/recibos-especiales",
    component: RecibosEspecialesView,
    title: "Definición de Recibos Especiales",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 234,
    code: "recibo-especial_GET",
    path: ["/recibo-especial/:mode", "/recibo-especial/:mode/:id"],
    component: ReciboEspecialView,
    title: "Definición de Recibo Especial",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 235,
    code: "especial_PUT",
    path: ["/pago-recibo-especial"],
    component: PagoReciboEspecialView,
    title: "Pago de Recibo Especial",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 232,
    code: "cuenta-prueba_GET",
    path: "/cuentas-prueba",
    component: CuentasPruebaView,
    title: "Cuentas de Prueba",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
//Escribanos
  {
    index: 86,
    code: "certificados-escribano_GET",
    path: "",
    component: null,
    title: "Escribanos",
    showHeader: true,
    nivelMenu: 1,
    children: [88]
  },
  {
    index: 88,
    code: "certificado-escribano_GET",
    path: "/certificados-escribano",
    component: CertificadosEscribanoView,
    title: "Certificados",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
//Legales
  {
    index: 130,
    path: "",
    component: null,
    title: "Legales",
    showHeader: true,
    nivelMenu: 1,
    children: [131,132,133,140,150,160,170]
  },
  {
    index: 131,
    code: "organo-judicial_GET",
    path: "/organos-judiciales",
    component: OrganosJudicialesView,
    title: "Organos Judiciales",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 132,
    code: "plantilla-documento_GET",
    path: "/plantillas-documentos",
    component: PlantillasDocumentosView,
    title: "Plantillas Documentos",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 133,
    code: "tipo-acto-procesal_GET",
    path: "/tipos-actos-procesales",
    component: TiposActosProcesalesView,
    title: "Tipos Actos Procesales",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 140,
    code: "tipo-relacion-certificado-apremio-persona_GET",
    path: "/tipo-relacion-certificado-apremio-persona",
    component: TipoRelacionesCertificadoApremioPersonaView,
    title: "Tipo Relaciones Certificado Persona",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 150,
    code: "certificado-apremio_GET",
    path: "/certificados-apremio",
    component: CertificadosApremiosView,
    title: "Certificados",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 151,
    code: "certificado-apremio_GET",
    path: ["/certificado-apremio/:mode", "/certificado-apremio/:mode/:id"],
    component: CertificadoApremioView,
    title: "Certificado",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 160,
    code: "certificado-apremio-item_GET",
    path: "/certificado-apremio-nuevo",
    component: CertificadoApremioItemsView,
    title: "Nuevo Certificado",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 170,
    code: "apremio_GET",
    path: "/apremios",
    component: ApremiosView,
    title: "Apremios",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 171,
    code: "apremio_GET",
    path: ["/apremio/:mode", "/apremio/:mode/:id"],
    component: ApremioView,
    title: "Apremio",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
//Configuración
  {
    index: 199,
    path: "",
    component: null,
    title: "Configuración",
    showHeader: true,
    nivelMenu: 1,
    children: [200,202,210,215,220,230]
  },
  {
    index: 200,
    code: "tasa_GET",
    path: "/tasas",
    component: TasasView,
    title: "Tasas",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 201,
    code: "tasa_GET",
    path: ["/tasa/:mode", "/tasa/:mode/:id"],
    component: TasaView,
    title: "Tasa",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 202,
    code: "sub-tasa_GET",
    path: "/sub-tasas",
    component: SubTasasView,
    title: "Sub Tasas",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 203,
    code: "sub-tasa_GET",
    path: ["/sub-tasa/:mode", "/sub-tasa/:mode/:id"],
    component: SubTasaView,
    title: "Sub tasa",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
  {
    index: 210,
    code: "variable_GET",
    path: "/variables",
    component: VariablesView,
    title: "Definición de Variables",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 215,
    code: "variable-global_GET",
    path: "/variables-globales",
    component: VariablesGlobalesView,
    title: "Variables Globales",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 220,
    code: "controlador_GET",
    path: "/controladores",
    component: ControladoresView,
    title: "Controladores",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 230,
    code: "entidad_GET",
    path: "/entidades",
    component: EntidadesView,
    title: "Listas",
    showHeader: true,
    nivelMenu: 2,
    children: []
  },
  {
    index: 231,
    code: "entidad_GET",
    path: "/entidad/:mode/:tipo",
    component: EntidadView,
    title: "Entidad",
    showHeader: true,
    nivelMenu: 0,
    children: []
  },
//not-found
  {
    index: 999,
    code: "not-found",
    path: "*",
    component: PageNotFoundView,
    title: "Página no encontrada",
    showHeader: false,
    nivelMenu: 0,
    children: []
  },
];
