
export const ORDENAMIENTO_GENERAL = {

    CUENTA: 120,
    NOMENCLATURA: 121,
    DOMICILIO: 122,
    DOMICILIO_PAR_IMPAR: 123,
    CONTROLADOR_DOMICILIO: 124,
    CONTROLADOR_DOMICILIO_PAR_IMPAR: 125
    
}