from .lista import Lista
from .contribuyente import Contribuyente
from .cuenta import Cuenta
from .inmueble import Inmueble
from .comercio import Comercio
from .vehiculo import Vehiculo
from .tasa import Tasa
from .sub_tasa import SubTasa
from .emision_definicion import EmisionDefinicion
from .emision import Emision
from .plan_pago_definicion import PlanPagoDefinicion
from .plan_pago import PlanPago
from .persona import Persona
from .certificado import Certificado
from .multa import Multa
