from .lista import Lista
from .contribuyente import Contribuyente
from .cuenta import Cuenta
from .inmueble import Inmueble
from .inmueble_valuacion import InmuebleValuacion
from .inmueble_superficie import InmuebleSuperficie
from .inmueble_frente import InmuebleFrente
from .comercio import Comercio
from .comercio_rubro import ComercioRubro
from .comercio_ddjj import ComercioDDJJ
from .vehiculo import Vehiculo
from .vehiculo_valuacion import VehiculoValuacion
from .tasa import Tasa
from .sub_tasa import SubTasa
from .emision_definicion import EmisionDefinicion
from .emision import Emision
from .plan_pago_definicion import PlanPagoDefinicion
from .plan_pago import PlanPago
from .plan_pago_cuota import PlanPagoCuota
from .persona import Persona
from .certificado import Certificado
from .multa import Multa
from .exencion import Exencion
from .regimen_moratoria import RegimenMoratoria
from .titular_cuenta import TitularCuenta
from .fondeadero import Fondeadero
from .servicio_medido import ServicioMedido, LecturaMedidor
from .puesto_mercado import PuestoMercado
from .derecho_construccion import DerechoConstruccion
from .valuacion_motor import ValorTierra, AlicuotaRubro
