USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE motivo_baja_rubro_comercio
GO

INSERT INTO rubro_bcra
SELECT
	cast(CODIGO as bigint) id,
	CODIGO,
	VALOR nombre,
	(ROW_NUMBER() OVER (ORDER BY CODIGO)) orden
FROM MAJOR_CAMPANA.DBO.LISTA_ESTATICA
WHERE NOMBRE='RubroBCRA' AND CODIGO<>'0'
ORDER BY id
GO
