USE LARAMIE_CAMPANA
GO

INSERT INTO tipo_vehiculo
SELECT
	ROW_NUMBER() OVER (ORDER BY COD_TIPO_VEHICULO) id,
	COD_TIPO_VEHICULO codigo,
	A.NOMBRE,
	ROW_NUMBER() OVER (ORDER BY COD_TIPO_VEHICULO) orden,
	inc.ID id_inciso_vehiculo
FROM MAJOR_CAMPANA.dbo.TIPO_VEHICULO A
	left join LARAMIE_CAMPANA.dbo.inciso_vehiculo inc on inc.codigo=A.COD_INCISO_VEHICULO
ORDER BY id
GO
