
export const FIRMA_TYPE = {

    TITULO_EJECUTIVO: 660,
    CERTIFICADO_LIBRE_DEUDA_AUTOMOTOR: 661,
    CERTIFICADO_BAJA_AUTOMOTOR: 662,
    CERTIFICADO_DEUDA_INMUEBLE: 663,
    CERTIFICADO_CATASTRAL: 664


}