import config from './config';

export const APIS = {
    URLS: {
        USUARIO: config.SITE.WEBAPI_SEGURIDAD + 'api/usuario',
        SESION: config.SITE.WEBAPI_SEGURIDAD + 'api/sesion',
        SEGURIDAD_PERFIL: config.SITE.WEBAPI_SEGURIDAD + 'api/perfil',
        CONFIGURACION: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/configuracion',
        PLAN_PAGO_DEFINICION: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/plan-pago-definicion',
        PAGO_CONTADO_DEFINICION: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/pago-contado-definicion',
        CUENTA_CORRIENTE_ITEM: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/cuenta-corriente-item',
        CUENTA_CORRIENTE_CONDICION_ESPECIAL: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/cuenta-corriente-condicion-especial',
        RECIBO_ESPECIAL: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/recibo-especial',
        CUENTA_PAGO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/cuenta-pago',
        CUENTA_PAGO_ITEM: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/cuenta-pago-item',
		CUENTA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/cuenta',
        COMERCIO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/comercio',
        FONDEADERO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/fondeadero',
        PAGO_CONTADO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/pago-contado',
        PLAN_PAGO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/plan-pago',
        TASA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/tasa',
        SUB_TASA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/sub-tasa',
        TIPO_MOVIMIENTO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/tipo-movimiento',
        TIPO_CONDICION_ESPECIAL: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/tipo-condicion-especial',
        VARIABLE: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/variable',
        RUBRO: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/rubro',
        INGRESOS_PUBLICOS_LISTA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/lista',
        ADMINISTRACION_LISTA: config.SITE.WEBAPI_ADMINISTRACION + 'api/lista',
        ADMINISTRACION_PERSONA_FISICA: config.SITE.WEBAPI_ADMINISTRACION + 'api/persona-fisica',
        ADMINISTRACION_PERSONA_JURIDICA: config.SITE.WEBAPI_ADMINISTRACION + 'api/persona-juridica',
        ADMINISTRACION_CUENTA_CONTABLE: config.SITE.WEBAPI_ADMINISTRACION + 'api/cuenta-contable',
        ADMINISTRACION_JURISDICCION: config.SITE.WEBAPI_ADMINISTRACION + 'api/jurisdiccion',
        ADMINISTRACION_RECURSO_POR_RUBRO: config.SITE.WEBAPI_ADMINISTRACION + 'api/recurso-por-rubro',
        REPORTE: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/reporte',
        MODELO_DECLARACION_JURADA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/modelo-declaracion-jurada',
        DECLARACION_JURADA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/declaracion-jurada',
        ESPECIAL: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/cuenta-especial',
        INMUEBLE: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/inmueble',
        PAIS: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/pais',
        PROVINCIA: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/provincia',
        LOCALIDAD: config.SITE.WEBAPI_INGRESOS_PUBLICOS + 'api/localidad',
    }
}
