--SELECT 'INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES ('||id::varchar||','''||codigo||''','''||tipo||''','''||nombre||''','||orden::varchar||');' FROM lista ORDER BY id ASC

TRUNCATE TABLE lista;

INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1,'1','EstadoCaja','Abierta',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (2,'2','EstadoCaja','Cerrada',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (3,'3','EstadoCaja','Inactiva',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (10,'1','TipoMovimientoCaja','Cobranza',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (11,'2','TipoMovimientoCaja','Retiro',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (12,'3','TipoMovimientoCaja','Ingreso',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (20,'1','MedioPago','Efectivo',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (21,'2','MedioPago','Tarjeta Débito',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (22,'3','MedioPago','Tarjeta Crédito',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (23,'4','MedioPago','Cheque',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (24,'5','MedioPago','Transferencia',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (30,'1','OrigenRecaudacion','Caja',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (31,'2','OrigenRecaudacion','Entidad recaudadora',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (32,'3','OrigenRecaudacion','Ingresos públicos',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (40,'1','MetodoImportacion','Archivo',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (41,'2','MetodoImportacion','API',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (42,'3','MetodoImportacion','No aplica',3);

INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1000,'1','Banco','Ciudad',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1001,'2','Banco','Provincia',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1002,'3','Banco','Nación',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1003,'4','Banco','Macro',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1010,'1','Emisor','Visa',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1011,'2','Emisor','Mastercard',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1012,'3','Emisor','Maestro',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1610,'1','LugarPago','DEBITO AUTOMATICO MASTER',1);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1611,'2','LugarPago','PAGO FACIL',2);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1612,'3','LugarPago','DEBITO BCO.PCIA.',3);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1613,'4','LugarPago','DEBITO AUTOMATICO VISA',4);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1614,'5','LugarPago','DEBITO AUTOMATICO AMERICAN EXPRESS',5);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1615,'6','LugarPago','GIRE',6);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1616,'7','LugarPago','DEBITO AUTOMATICO PAGO DIRECTO',7);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1617,'8','LugarPago','DEBITO AUTOMATICO DINERS',8);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1618,'9','LugarPago','DEBITO AUTOMATICO CABAL',9);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1619,'10','LugarPago','BANELCO',10);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1620,'11','LugarPago','BCO.PROVINCIA BS.AS.',11);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1621,'12','LugarPago','HOSPITAL DE TIGRE',12);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1622,'13','LugarPago','BCO. PCIA. SUC. PACHECO',13);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1623,'14','LugarPago','BCO. PCIA. SUC. TORCUATO',14);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1624,'15','LugarPago','RAPIPAGO',15);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1625,'16','LugarPago','BAPRO PAGOS',16);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1626,'17','LugarPago','BCO.PCIA. SAM2000',17);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1627,'18','LugarPago','LINK',18);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1628,'19','LugarPago','SERVICIO PAGOS VISA',19);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1629,'21','LugarPago','BCO. RIO',20);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1630,'22','LugarPago','BCO. BUEN AYRE',21);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1631,'31','LugarPago','TESORERIA MUNICIPAL',22);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1632,'32','LugarPago','DELEG. PACHECO',23);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1633,'33','LugarPago','DELEG. TORCUATO OESTE',24);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1634,'34','LugarPago','DELEG. TALAR',25);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1635,'35','LugarPago','DELEG. BENAVIDEZ',26);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1636,'36','LugarPago','DELEG. DIQUE LUJAN',27);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1637,'37','LugarPago','BCO. CREDICOOP',28);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1638,'38','LugarPago','COOPERATIVA PACHECO',29);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1639,'39','LugarPago','DELEG. T. DEL TALAR',30);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1640,'40','LugarPago','LIBRETAS SANITARIAS',31);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1641,'41','LugarPago','DELEG. RICARDO ROJAS',32);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1642,'42','LugarPago','MUSEO DE ARTE',33);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1643,'43','LugarPago','PUERTO DE FRUTOS',34);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1644,'44','LugarPago','DELEG. RINCON DE MILBERG',35);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1645,'45','LugarPago','DELEG. TORCUATO ESTE',36);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1646,'46','LugarPago','CEMENTERIOS',37);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1647,'47','LugarPago','SECRETARIA DE GOBIERNO',38);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1648,'48','LugarPago','BANCO GALICIA',39);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1649,'49','LugarPago','HOSPITAL ODONTOLOGICO',40);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1650,'50','LugarPago','P.T. MASTERCARD',41);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1651,'51','LugarPago','P.T. VISA',42);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1652,'52','LugarPago','P.T. AMERICAN EXPRESS',43);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1653,'53','LugarPago','P.T. DINERS CLUB',44);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1654,'54','LugarPago','P.T. CABAL',45);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1655,'55','LugarPago','VISA INTERNET',46);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1656,'56','LugarPago','AMERICAN INTERNET',47);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1657,'57','LugarPago','DINERS INTERNET',48);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1658,'58','LugarPago','MASTERCARD INTERNET',49);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1659,'59','LugarPago','DEBITO AUTOMATICO HABERES',50);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1660,'60','LugarPago','INTERBANKING',51);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1661,'61','LugarPago','SUCERP',52);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1662,'62','LugarPago','AMARRAS HUGO DEL CARRIL',53);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1663,'63','LugarPago','QUIWI',54);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1664,'64','LugarPago','HOSPITAL OFTALMOLOGICO',55);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1665,'65','LugarPago','VISA INTERNET - SPS DECIDIR',56);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1666,'66','LugarPago','CENTRO DIAGNOSTICO POR IMAGENES',57);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1667,'67','LugarPago','AMARRAS RODOLFO WALSH',58);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1668,'68','LugarPago','CANCELACION DE CHEQUE DIFERIDO',59);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1669,'69','LugarPago','TRANSITO',60);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1670,'70','LugarPago','MACRO CLICK DE PAGOS',61);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1671,'125','LugarPago','MERCADOPAGO',62);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1672,'27','LugarPago','CAJAS',63);
INSERT INTO lista(id,codigo,tipo,nombre,orden) VALUES (1673,'99','LugarPago','E-PAGOS',99);
