TRUNCATE TABLE entidad_definicion;

INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (1, 'EstadoCaja', 'Estado de caja', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (2, 'TipoMovimientoCaja', 'Tipo movimiento de caja', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (3, 'MedioPago', 'Medio de pago', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (4, 'OrigenRecaudacion', 'Origen de recaudación', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (5, 'LugarPago', 'Lugar de pago', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (6, 'Recaudadora', 'Recaudadora', 'codigoCliente', 'idLugarPago', 'idMetodoImportacion', '', '', '', '', '', '', '', 'Código de cliente', 'Lugar de pago', 'Método de importación', '', '', '', '', '', '', '', 'string', 'list', 'list', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (7, 'Dependencia', 'Dependencia', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (8, 'Caja', 'Caja', 'idDependencia', 'idRecaudadora', '', '', '', '', '', '', '', '', 'Dependencia', 'Recaudadora', '', '', '', '', '', '', '', '', 'entity', 'entity', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (9, 'Banco', 'Banco', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
INSERT INTO entidad_definicion (id, tipo, descripcion, nombre_1, nombre_2, nombre_3, nombre_4, nombre_5, nombre_6, nombre_7, nombre_8, nombre_9, nombre_10, descripcion_1, descripcion_2, descripcion_3, descripcion_4, descripcion_5, descripcion_6, descripcion_7, descripcion_8, descripcion_9, descripcion_10, tipo_dato_1, tipo_dato_2, tipo_dato_3, tipo_dato_4, tipo_dato_5, tipo_dato_6, tipo_dato_7, tipo_dato_8, tipo_dato_9, tipo_dato_10, obligatorio_1, obligatorio_2, obligatorio_3, obligatorio_4, obligatorio_5, obligatorio_6, obligatorio_7, obligatorio_8, obligatorio_9, obligatorio_10)
    VALUES (10, 'Emisor', 'Emisor', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', false, false, false, false, false, false, false, false, false, false);
