USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE recurso_por_rubro
GO

INSERT INTO recurso_por_rubro
SELECT 
	 ROW_NUMBER() OVER (ORDER BY EJERCICIO, AGRUPAMIENTO) id
	--,COD_RECURSO_POR_RUBRO codigo
	,AGRUPAMIENTO codigo
	,NOMBRE
	,ROW_NUMBER() OVER (ORDER BY EJERCICIO, AGRUPAMIENTO) orden
	,PRESUPUESTO
	,AGRUPAMIENTO
	,PROCEDENCIA
	,CARACTER_ECONOMICO
	,NIVEL
	,MAJOR_CAMPANA.dbo.GET_FECHA(FECHA_BAJA) fecha_baja
	,DETALLE
	,EJERCICIO
FROM MAJOR_CAMPANA.dbo.RECURSO_POR_RUBRO
WHERE LEN(NOMBRE) > 0
ORDER BY EJERCICIO, AGRUPAMIENTO
GO
