USE MAJOR_CAMPANA
GO

ALTER TABLE SUB_TASA ALTER COLUMN IMPUESTO_NACIONAL numeric(18,2) null
ALTER TABLE SUB_TASA ALTER COLUMN IMPUESTO_PROVINCIAL numeric(18,2) null
ALTER TABLE SUB_TASA ALTER COLUMN CTAS_CTES numeric(18,2) null
GO
