from .contribuyentes import router as contribuyentes_router
from .cuentas import router as cuentas_router
from .inmuebles import router as inmuebles_router
from .inmueble_valuaciones import router as inmueble_valuaciones_router
from .inmueble_superficies import router as inmueble_superficies_router
from .inmueble_frentes import router as inmueble_frentes_router
from .padron import router as padron_router
from .vehiculos import router as vehiculos_router
from .vehiculo_valuaciones import router as vehiculo_valuaciones_router
from .comercios import router as comercios_router
from .comercio_rubros import router as comercio_rubros_router
from .comercio_ddjj import router as comercio_ddjj_router
from .emisiones import router as emisiones_router
from .planes_pago import router as planes_pago_router
from .listas import router as listas_router
from .certificados import router as certificados_router
from .multas import router as multas_router
from .tasas import router as tasas_router
from .sub_tasas import router as sub_tasas_router
from .personas import router as personas_router
from .exenciones import router as exenciones_router
from .titulares import router as titulares_router
from .regimenes_moratoria import router as regimenes_moratoria_router
from .fondeaderos import router as fondeaderos_router
from .servicios_medidos import router as servicios_medidos_router
from .puestos_mercado import router as puestos_mercado_router
from .derechos_construccion import router as derechos_construccion_router
from .valuacion_motor import valor_tierra_router, alicuota_router, motor_router
