/*
SELECT
'('||cast(id as varchar)||','''||codigo||''','''||descripcion||''','||COALESCE(cast(id_tipo_tributo as varchar),'null')||','''||tipo_dato||''','||cast(constante as varchar)||','||cast(predefinido as varchar)||','||cast(opcional as varchar)||','||cast(activo as varchar)||','||cast(global as varchar)||',''''),'
FROM variable WHERE id>=1000 ORDER BY id;
*/

--Variables globales
DELETE FROM variable WHERE id >= 1000;

INSERT INTO variable(id, codigo, descripcion, id_tipo_tributo, tipo_dato, constante, predefinido, opcional, activo, global,lista)
VALUES
(1008,'CUENTA_CORRIENTE_SUBTASA_HONORARIOS','Subtasa de Honorarios de Abogados',null,'string',true,true,false,true,true,''),
(1009,'CUENTA_CORRIENTE_SUBTASA_APORTES','Subtasa de Aportes de Abogados',null,'string',true,true,false,true,true,''),
(1010,'CUENTA_CORRIENTE_SUBTASA_RECARGOS','Subtasa de Recargos por deuda',null,'string',true,true,false,true,true,''),
(1011,'CUENTA_CORRIENTE_INTERES_RECARGOS','Interés de Recargos por deuda',null,'decimal',false,true,false,true,true,''),
(1012,'CUENTA_CORRIENTE_CANTIDAD_JUS_HONORARIOS','Cantidad de JUS para Honorarios de Abogados',null,'number',true,true,false,true,true,''),
(1013,'CUENTA_CORRIENTE_PORCENTAJE_APORTES','Porcentaje de Aportes de Abogados',null,'decimal',true,true,false,true,true,''),
(1014,'CUENTA_CORRIENTE_IMPORTE_SELLADOS','Importe de Sellados (Planes de Pago)',null,'decimal',true,true,false,true,true,''),
(1015,'CUENTA_CORRIENTE_PORCENTAJE_GASTOS_CAUSIDICOS','Porcentaje de Gastos Causídicos',null,'decimal',true,true,false,true,true,''),
(1016,'CUENTA_CORRIENTE_CODIGO_DELEGACION_RECIBOS','Código de Delegación de Recibos en general',null,'string',true,true,false,true,true,''),
(1017,'CUENTA_CORRIENTE_CODIGO_DELEGACION_PAGO_CONTADO','Código de Delegación de Recibos de Pago Contado',null,'string',true,true,false,true,true,''),
(1018,'CUENTA_CORRIENTE_DIAS_VENCIMIENTO_RECIBOS','Cantidad de días de vencimiento de Recibos en general',null,'number',true,true,false,true,true,''),
(1020,'UF','Unidad Fija',null,'decimal',false,true,false,true,true,''),
(1021,'MODULO','Valor Módulo',null,'decimal',false,true,false,true,true,''),
(1022,'MINIMO','Valor Mínimo Régimen General',null,'decimal',false,true,false,true,true,''),
(1023,'CUENTA_CORRIENTE_TASA_APORTES','Tasa de Aportes de Abogados',null,'string',true,true,false,true,true,''),
(1024,'CUENTA_CORRIENTE_TASA_RECARGOS','Tasa de Recargos por deuda',null,'string',false,true,false,true,true,''),
(1025,'CUENTA_CORRIENTE_TASA_HONORARIOS','Tasa de Honorarios de Abogados',null,'string',true,true,false,true,true,''),
(1026,'CUENTA_CORRIENTE_TASA_MULTAS','Tasa de Multas',null,'string',true,true,false,true,true,''),
(1027,'CUENTA_CORRIENTE_SUBTASA_MULTAS','Subtasa de Multas',null,'string',true,true,false,true,true,''),
(1030,'JUS','Jus arancelario',null,'decimal',true,true,false,true,true,''),
(1031,'COMERCIO_CANTIDAD_UF_MULTA_DDJJ_FUERA_TERMINO','Cantidad de UF por Multa en Presentación de DDJJ fuera de término',null,'number',false,true,true,true,true,''),
(1033,'CUENTA_CORRIENTE_CODIGO_DELEGACION_ARBA_VEHICULO','Código de Delegación de ARBA Vehículos',null,'string',true,true,false,true,true,''),
(1034,'CUENTA_CORRIENTE_TASA_ARBA_VEHICULO_MORATORIA','Tasa de ARBA Vehículos (Moratoria)',null,'string',true,true,false,true,true,''),
(1035,'CUENTA_CORRIENTE_SUBTASA_ARBA_VEHICULO_MORATORIA','Subtasa de ARBA Vehículos (Moratoria)',null,'string',true,true,false,true,true,''),
(1036,'CUENTA_CORRIENTE_TASA_ARBA_VEHICULO_DEUDA','Tasa de ARBA Vehículos (Deuda)',null,'string',true,true,false,true,true,''),
(1037,'CUENTA_CORRIENTE_SUBTASA_ARBA_VEHICULO_DEUDA','Subtasa de ARBA Vehículos (Deuda)',null,'string',true,true,false,true,true,''),
(1038,'CUENTA_CORRIENTE_TASA_INTERES','Tasa de Interes',null,'string',true,true,false,true,true,''),
(1039,'CUENTA_CORRIENTE_SUBTASA_INTERES','Subtasa de Interes',null,'string',true,true,false,true,true,''),
(2000,'RECARGO_COEFICIENTE','Coeficiente de recargo',null,'decimal',false,true,false,true,true,''),
(2001,'DESC_PAGO_EN_TERMINO','Coeficiente de descuento por pago en término',null,'decimal',false,true,false,true,true,''),
(2002,'C_IMPORTE_ACREDITACION','Importe acreditación',null,'decimal',false,true,false,true,true,''),
(2003,'DDJJ_TOPEMINIMO','Importe tope mínimo para declaraciones juradas',null,'decimal',false,true,false,true,true,''),
(2004,'DDJJ_TOPEMAXIMO','Importe tope máximo para declaraciones juradas',null,'decimal',false,true,false,true,true,''),
(2005,'RECDESC_PORC_ANTENAS_ESTRUCTURAS','Coeficiente de recargo por estructuras',null,'decimal',false,true,false,true,true,''),
(2006,'RECDESC_PORC_ANTENAS_SISTEMAS','Coeficiente de recargo por sistemas',null,'decimal',false,true,false,true,true,''),
(2007,'RECDESC_PORC_ANTENAS_WICAPS','Coeficiente de recargo por WICAPS',null,'decimal',false,true,false,true,true,''),
(2008,'MARQUESINA','Valor de marquesina',null,'decimal',false,true,false,true,true,''),
(2009,'RECDESC_PORC_PYP','Coeficiente de recargo para tasa Publicidad y Propaganda',null,'decimal',false,true,false,true,true,''),
(2010,'PYP_IMP_ANUNCIANTES','Importe por inscripción de registro de publicidad por anunciantes',null,'decimal',false,true,false,true,true,''),
(2011,'PYP_IMP_TARJETAS','Importe por inscripción de registro de publicidad de tarjetas de crédito',null,'decimal',false,true,false,true,true,''),
(2012,'IMP_ESTACIONFLUVIAL','Importe según ordenanza para estación fluvial',null,'decimal',false,true,false,true,true,''),
(2013,'IMP_TURISMO','Importe según ordenanza para embarcaciones de turismo',null,'decimal',false,true,false,true,true,''),
(2014,'IMP_ALQUILER','Valor según ordenanza para lanchas de alquiler',null,'decimal',false,true,false,true,true,''),
(2015,'PORC_PROTECCION_CIUDADANA','Coeficiente de recargo por contribución de protección ciudadana',null,'decimal',false,true,false,true,true,''),
(2016,'PORC_CONTRIB_HOSPITAL','Coeficiente de recargo por contribución de hospital',null,'decimal',false,true,false,true,true,''),
(2017,'VALOR_ENVIO_POSTAL','Costo de envío postal',null,'decimal',false,true,false,true,true,''),
(2018,'PORC_VALUACION_DNRPA','[Motovehículos] Porcentaje Valuacion DNRPA',null,'decimal',false,true,false,true,true,''),
(2019,'REC_SUP_20K','[Inmuebles] Recargo superficie superior a 20.000m',null,'decimal',false,true,false,true,true,''),
(2020,'REC_MACIZO_SD','[Inmuebles] Recargo - Macizo mayor a 10.000m2 sin desarrollar',null,'decimal',false,true,false,true,true,''),
(2021,'RED_UC_20M','[Inmuebles] Reducción - Unidad Complementaria MENOR a 20m2',null,'decimal',false,true,false,true,true,''),
(2022,'RED_UC_21M','[Inmuebles] Reducción - Unidad complementaria MAYOR a 20m2',null,'decimal',false,true,false,true,true,''),
(2023,'ALICUOTA_INCISOS','[Vehiculos] Alicuota para incisos diferentes al A',null,'decimal',false,true,false,true,true,''),
(2024,'CUENTA_CORRIENTE_TASA_MAYOR_A','Tasa de Gastos Causídicos Mayor A',null,'string',false,true,false,true,true,''),
(2025,'CUENTA_CORRIENTE_TASA_MAYOR_C','Tasa de Gastos Causídicos Mayor C',null,'string',false,true,false,true,true,''),
(2026,'CUENTA_CORRIENTE_TASA_MOROSIDAD','Tasa de Morosidad',null,'string',false,true,false,true,true,''),
(2027,'CUENTA_CORRIENTE_TASA_RECARGOS_PROTECCION_CIUDADANA','Tasa de Recargos por Protección Ciudadana',null,'string',false,true,false,true,true,''),
(2028,'CUENTA_CORRIENTE_SUBTASA_MAYOR_A','Subtasa de Gastos Causídicos Mayor A',null,'string',false,true,false,true,true,''),
(2029,'CUENTA_CORRIENTE_SUBTASA_MAYOR_C','Subtasa de Gastos Causídicos Mayor C',null,'string',false,true,false,true,true,''),
(2030,'CUENTA_CORRIENTE_SUBTASA_MOROSIDAD','Subtasa de Morosidad',null,'string',false,true,false,true,true,''),
(2031,'CUENTA_CORRIENTE_SUBTASA_RECARGOS_PROTECCION_CIUDADANA','Subtasa de Recargos por Protección Ciudadana',null,'string',false,true,false,true,true,''),
(2032,'CUENTA_CORRIENTE_TASA_SELLADOS','Tasa de Sellados',null,'string',false,true,false,true,true,''),
(2033,'CUENTA_CORRIENTE_SUBTASA_SELLADOS','Subtasa de Sellados',null,'string',false,true,false,true,true,'');
