export const EMISION_STATE = {
    READ_PENDING: 'READ_PENDING',
    READ_SUCCESS: 'READ_SUCCESS',
    READ_ERROR: 'READ_ERROR',
    WORK_SUCCESS: 'WORK_SUCCESS',
    WORK_ERROR: 'WORK_ERROR',
    WRITE_SUCCESS: 'WRITE_SUCCESS',
    WRITE_ERROR: 'WRITE_ERROR'
}
