USE MAJOR_CAMPANA
GO

--ALTER TABLE VEHICULO ADD CALLE_ENTREGA NVARCHAR(255) null
--ALTER TABLE VEHICULO ADD ALTURA_ENTREGA INT null
--ALTER TABLE VEHICULO ADD PISO_ENTREGA NCHAR(10) null
--ALTER TABLE VEHICULO ADD DEPTO_ENTREGA NCHAR(10) null

--ALTER TABLE FONDEADERO ADD CALLE_ENTREGA NVARCHAR(255) null
--ALTER TABLE FONDEADERO ADD ALTURA_ENTREGA INT null
--ALTER TABLE FONDEADERO ADD PISO_ENTREGA NCHAR(10) null
--ALTER TABLE FONDEADERO ADD DEPTO_ENTREGA NCHAR(10) null
--ALTER TABLE FONDEADERO ADD EMAIL_ZONA_ENTREGA NVARCHAR(255) null

--VEHICULO: cambiar nombre NUMERO_ENTREGA por ALTURA_ENTREGA

ALTER TABLE RECARGO_DESCUENTO ALTER COLUMN COD_TASA NVARCHAR(50) null
ALTER TABLE RECARGO_DESCUENTO ALTER COLUMN COD_SUBTASA NVARCHAR(50) null

ALTER TABLE VARIABLES_CUENTA ALTER COLUMN FECHA_DESDE datetime null
ALTER TABLE VARIABLES_CUENTA ALTER COLUMN FECHA_HASTA datetime null

ALTER TABLE ACTO_PROCESAL ALTER COLUMN FECHA_DESDE datetime null
ALTER TABLE ACTO_PROCESAL ALTER COLUMN FECHA_HASTA datetime null

ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_INTIMACION datetime null
ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_PRESENTACION datetime null
ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_VIGENTE_DESDE datetime null
ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_REGISTRADO datetime null
ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_PERMISO_PROVISORIO datetime null
ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_APROBACION datetime null
ALTER TABLE SUPERFICIE ALTER COLUMN FECHA_FIN_OBRA datetime null
GO
