USE MAJOR_CAMPANA
GO

/*
DELETE FROM LISTA WHERE NOMBRE='Cementerio' AND CODIGO IN ('1','2')
DELETE FROM LISTA WHERE NOMBRE='TipoDestinoInhumacion' AND VALOR = 'DEPOSITO DE RESTOS'
UPDATE LISTA SET NOMBRE='Cementerio' WHERE NOMBRE='cementerioinstitucion'
UPDATE LISTA SET NOMBRE='CondicionFiscal' WHERE NOMBRE='condicionfiscal'
UPDATE LISTA SET NOMBRE='IngresosBrutos' WHERE NOMBRE='ingresosbrutos'
UPDATE LISTA SET NOMBRE='TipoMinimoAplicable' WHERE NOMBRE='tipominimoaplicable'
UPDATE LISTA_DINAMICA SET NOMBRE='OrigenDeclaracionJurada' WHERE NOMBRE='origendeclaracionjurada'
GO
*/

UPDATE PERSONA SET NUMERO_DOCUMENTO=ID_PERSONA WHERE LEN(NUMERO_DOCUMENTO)=0
GO

UPDATE CONTROLADOR SET ID_CONTROLADOR=NUMERO
GO

INSERT INTO dbo.VARIABLES_CUENTA(COD_TIPO_TRIBUTO,NUMERO_CUENTA,NOMBRE,VALOR,FECHA_DESDE,FECHA_HASTA)
    SELECT '1', NUMERO_CUENTA, 'CATEGORIA_ORIGINAL', CAST(CAT_ORIGINAL AS VARCHAR(50)), '1900-01-01 00:00:00.000', '2100-01-01 00:00:00.000' FROM INMUEBLE
	 UNION
    SELECT '1', NUMERO_CUENTA, 'CATEGORIA_OFI16', CAST(CAT_OFI16 AS VARCHAR(50)), '1900-01-01 00:00:00.000', '2100-01-01 00:00:00.000' FROM INMUEBLE
	 UNION
    SELECT '1', NUMERO_CUENTA, 'CATEGORIA_2024', CAST(CAT_2024 AS VARCHAR(50)), '1900-01-01 00:00:00.000', '2100-01-01 00:00:00.000' FROM INMUEBLE
GO

UPDATE Cartel
SET
	COD_TASA=NULL,
	COD_SUB_TASA=NULL
GO

-- UPDATE DDJJ
-- SET
-- 	COD_TASA=MT.Tasa,
-- 	COD_SUBTASA=MT.SubTasa+MT.Item
-- FROM
-- 	DECLARACION_JURADA DDJJ
-- 	INNER JOIN _MIGRA_TASAS MT ON MT.TasaMAJOR=DDJJ.COD_TASA AND MT.SubTasaMAJOR=DDJJ.COD_SUBTASA
-- GO

UPDATE RD
SET
	COD_TASA=MT.Tasa,
	COD_SUBTASA=MT.SubTasa+MT.Item
FROM
	RECARGO_DESCUENTO RD
	INNER JOIN _MIGRA_TASAS MT ON MT.TasaMAJOR= RD.COD_TASA AND MT.SubTasaMAJOR= RD.COD_SUBTASA
GO

----INSERTO LAS CUENTAS DUPLICADAS DE COMERCIO COMO RELACIONES CON INMUEBLES
--TRUNCATE TABLE RELACION_ENTRE_CUENTAS
--GO
--INSERT INTO RELACION_ENTRE_CUENTAS
--SELECT
--	2 TIPO_TRIBUTO_1,
--	NUMERO_CUENTA NUMERO_CUENTA_1,
--	1 TIPO_TRIBUTO_2,
--	NUMERO_CUENTA_INMUEBLE_RELACIONADO NUMERO_CUENTA_2,
--	'Inmueble relacionado al comercio con Nro de Cuenta ' + NUMERO_CUENTA DETALLE_RELACION
--FROM COMERCIO
--WHERE NUMERO_CUENTA IN (SELECT NUMERO_CUENTA FROM COMERCIO GROUP BY NUMERO_CUENTA HAVING COUNT(1)>1)
--ORDER BY NUMERO_CUENTA, NUMERO_CUENTA_INMUEBLE_RELACIONADO
--GO

----BORRO CUENTAS DUPLICADAS DE COMERCIO
--DELETE COMERCIO
--WHERE NUMERO_CUENTA IN
--(
--	SELECT NUMERO_CUENTA
--	FROM COMERCIO GROUP BY NUMERO_CUENTA HAVING COUNT(1)>1
--)
--AND NOT NUMERO_CUENTA+'|'+NUMERO_CUENTA_INMUEBLE_RELACIONADO IN
--(
--	SELECT NUMERO_CUENTA+'|'+MAX(NUMERO_CUENTA_INMUEBLE_RELACIONADO) MAX_INMUEBLE
--	FROM COMERCIO GROUP BY NUMERO_CUENTA HAVING COUNT(1)>1
--)
--GO

--- BORRO PERSONAS FISICAS DUPLICADAS CON PERSONAS JURIDICAS

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRAN;

    DECLARE @DO_DELETE bit = 1;  -- 0 = preview, 1 = ejecutar borrado

    IF OBJECT_ID('tempdb..#Candidatos') IS NOT NULL DROP TABLE #Candidatos;

    -- Materializamos candidatos en temp table para poder reutilizar
    SELECT
        pf.COD_TIPO_PERSONA,
        pf.ID_PERSONA,
        pf.COD_TIPO_DOCUMENTO,
        pf.NUMERO_DOCUMENTO
    INTO #Candidatos
    FROM dbo.PERSONA_FISICA pf
    WHERE EXISTS (
        SELECT 1
        FROM dbo.PERSONA_JURIDICA pj
        WHERE pj.COD_TIPO_PERSONA = pf.COD_TIPO_PERSONA
          AND LTRIM(RTRIM(pj.ID_PERSONA)) = LTRIM(RTRIM(pf.ID_PERSONA))
    );

    -- Preview
    SELECT COUNT(*) AS total_candidatos FROM #Candidatos;

    SELECT TOP (20) *
    FROM #Candidatos
    ORDER BY ID_PERSONA;

    IF @DO_DELETE = 1
        BEGIN
            -- Borrado usando WHERE EXISTS contra la temp table (evita warning del linter)
            DELETE pf
            FROM dbo.PERSONA_FISICA pf
            WHERE EXISTS (
                SELECT 1
                FROM #Candidatos c
                WHERE c.COD_TIPO_PERSONA = pf.COD_TIPO_PERSONA
                  AND LTRIM(RTRIM(c.ID_PERSONA)) = LTRIM(RTRIM(pf.ID_PERSONA))
            );

            PRINT CONCAT('Filas borradas en PERSONA_FISICA: ', @@ROWCOUNT);
        END
    ELSE
        BEGIN
            PRINT 'Modo preview: no se realizaron borrados (setear @DO_DELETE = 1 para ejecutar).';
        END

    COMMIT;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK;
    THROW;
END CATCH;
