USE MAJOR_CAMPANA
GO

CREATE TABLE CUENTA_CORRIENTE
(
--CAMPOS DE IDENTIFICACION
	COD_TIPO_TRIBUTO NUMERIC(18,0), 
    NUMERO_CUENTA VARCHAR(50), 
    NUMERO_PARTIDA NUMERIC(18,0) NULL, 
	COD_RUBRO VARCHAR(50) NULL, 
	COD_TASA VARCHAR(50) NULL, 
	COD_SUBTASA VARCHAR(50) NULL, 
    PERIODO VARCHAR(50) NULL, 
    CUOTA NUMERIC(18,0) NULL, 
--AGRUPADOR
    TASA_CABECERA VARCHAR(50) NULL, 
--VALORES
    COD_TIPO_MOVIMIENTO NUMERIC(18,0) NULL, 
    IMPORTE_DEBE NUMERIC(18,2) NULL, 
    IMPORTE_HABER NUMERIC(18,2) NULL,
    FECHA_VENCIMIENTO1 DATETIME NULL, 
    FECHA_VENCIMIENTO2 DATETIME NULL, 
--REFERENCIAS
    NUMERO_EMISION VARCHAR(50), 
    NUMERO_CERTIFICADO_APREMIO NUMERIC(18,0), 
    COD_PLAN_PAGO NUMERIC(18,0), 
--CAMPOS INFORMATIVOS
    CODIGO_DELEGACION VARCHAR(50) NULL, 
    NUMERO_MOVIMIENTO NUMERIC(18,0) NULL, 
    NUMERO_ITEM NUMERIC(18,0) NULL, 
    COD_LUGAR_PAGO NUMERIC(18,0) NULL, 
    DETALLE VARCHAR(250) NULL,
    USUARIO_PROCESO VARCHAR(250) NULL,
    FECHA_PROCESO DATETIME NULL, 
    FECHA_COBRO  DATETIME NULL
)