-- Rubros reales de la tabla original
SELECT
    RIGHT(REPLICATE('0', 20) + CAST(Legajo AS VARCHAR) + RIGHT('00' + CAST(Sublegajo AS VARCHAR), 2), 20) AS NUMERO_CUENTA,
    CAST(CodigoRubro AS VARCHAR) AS COD_RUBRO,
    0 AS COD_UBICACION_COMERCIO,
    1 AS COD_RUBRO_LIQUIDACION,
    1 AS COD_RUBRO_PROVINCIA,
    0 AS COD_RUBRO_BCRA,
    '' AS DESCRIPCION,
    '' AS ES_DE_OFICIO,
    CASE 
        WHEN Cese IS NULL THEN 1
        ELSE 0
    END AS ES_RUBRO_PRINCIPAL,
    'S' AS ES_CON_DDJJ,
    FechaInicio AS FECHA_INICIO,
    FechaBaja AS FECHA_CESE,
    NULL AS FECHA_ALTA_TRANSITORIA,
    NULL AS FECHA_BAJA_TRANSITORIA,
    FechaBaja AS FECHA_BAJA,
    0 AS COD_MOTIVO_BAJA_COMERCIO
FROM ContribuyentesRubrosClipper

UNION ALL

-- Rubro genérico 999999 adicional por cada cuenta
SELECT
    RIGHT(REPLICATE('0', 20) + CAST(Legajo AS VARCHAR) + RIGHT('00' + CAST(Sublegajo AS VARCHAR), 2), 20) AS NUMERO_CUENTA,
    '999999' AS COD_RUBRO,
    0 AS COD_UBICACION_COMERCIO,
    1 AS COD_RUBRO_LIQUIDACION,
    1 AS COD_RUBRO_PROVINCIA,
    0 AS COD_RUBRO_BCRA,
    '' AS DESCRIPCION,
    '' AS ES_DE_OFICIO,
    0 AS ES_RUBRO_PRINCIPAL,
    'S' AS ES_CON_DDJJ,
    FechaInicio AS FECHA_INICIO,
    NULL AS FECHA_CESE,
    NULL AS FECHA_ALTA_TRANSITORIA,
    NULL AS FECHA_BAJA_TRANSITORIA,
    NULL AS FECHA_BAJA,
    0 AS COD_MOTIVO_BAJA_COMERCIO
FROM (
    SELECT DISTINCT Legajo, Sublegajo, MIN(FechaInicio) AS FechaInicio
    FROM ContribuyentesRubrosClipper
    GROUP BY Legajo, Sublegajo
) AS cuentas;
