SELECT
    -- ID
    CAST(IdTripartito AS BIGINT) AS ID,

    -- PARTIDA Y DIGITO_VERIFICADOR
    CAST(Partida AS NVARCHAR(50)) AS PARTIDA,
    CAST(Dígitoverificador AS NVARCHAR(20)) AS DIGITO_VERIFICADOR,

    -- PARTIDO Y CIRCUNSCRIPCION
    CAST(Partido AS NVARCHAR(20)) AS PARTIDO,
    CAST(Circunscripcion AS NVARCHAR(20)) AS CIRCUNSCRIPCION,

    -- SECCION
    CAST(Seccion AS NVARCHAR(20)) AS SECCION,

    -- CHACRA / LETRA_CHACRA
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Chacra AS NVARCHAR(20)),1)) = 1 THEN
            LEFT(CAST(Chacra AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Chacra AS NVARCHAR(20)) + 'X') -1)
        ELSE
            ''
    END AS CHACRA,
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Chacra AS NVARCHAR(20)),1)) = 1 THEN
            SUBSTRING(CAST(Chacra AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Chacra AS NVARCHAR(20)) + 'X'), LEN(CAST(Chacra AS NVARCHAR(20))))
        ELSE
            CAST(Chacra AS NVARCHAR(20))
    END AS LETRA_CHACRA,

    -- QUINTA / LETRA_QUINTA
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Quinta AS NVARCHAR(20)),1)) = 1 THEN
            LEFT(CAST(Quinta AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Quinta AS NVARCHAR(20)) + 'X') -1)
        ELSE
            ''
    END AS QUINTA,
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Quinta AS NVARCHAR(20)),1)) = 1 THEN
            SUBSTRING(CAST(Quinta AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Quinta AS NVARCHAR(20)) + 'X'), LEN(CAST(Quinta AS NVARCHAR(20))))
        ELSE
            CAST(Quinta AS NVARCHAR(20))
    END AS LETRA_QUINTA,

    -- FRACCION / LETRA_FRACCION
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Fraccion AS NVARCHAR(20)),1)) = 1 THEN
            LEFT(CAST(Fraccion AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Fraccion AS NVARCHAR(20)) + 'X') -1)
        ELSE
            ''
    END AS FRACCION,
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Fraccion AS NVARCHAR(20)),1)) = 1 THEN
            SUBSTRING(CAST(Fraccion AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Fraccion AS NVARCHAR(20)) + 'X'), LEN(CAST(Fraccion AS NVARCHAR(20))))
        ELSE
            CAST(Fraccion AS NVARCHAR(20))
    END AS LETRA_FRACCION,

    -- MANZANA / LETRA_MANZANA
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Manzana AS NVARCHAR(20)),1)) = 1 THEN
            LEFT(CAST(Manzana AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Manzana AS NVARCHAR(20)) + 'X') -1)
        ELSE
            ''
    END AS MANZANA,
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Manzana AS NVARCHAR(20)),1)) = 1 THEN
            SUBSTRING(CAST(Manzana AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Manzana AS NVARCHAR(20)) + 'X'), LEN(CAST(Manzana AS NVARCHAR(20))))
        ELSE
            CAST(Manzana AS NVARCHAR(20))
    END AS LETRA_MANZANA,

    -- PARCELA / LETRA_PARCELA
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Parcela AS NVARCHAR(20)),1)) = 1 THEN
            LEFT(CAST(Parcela AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Parcela AS NVARCHAR(20)) + 'X') -1)
        ELSE
            ''
    END AS PARCELA,
    CASE 
        WHEN ISNUMERIC(LEFT(CAST(Parcela AS NVARCHAR(20)),1)) = 1 THEN
            SUBSTRING(CAST(Parcela AS NVARCHAR(20)), PATINDEX('%[^0-9]%', CAST(Parcela AS NVARCHAR(20)) + 'X'), LEN(CAST(Parcela AS NVARCHAR(20))))
        ELSE
            CAST(Parcela AS NVARCHAR(20))
    END AS LETRA_PARCELA,

    -- SUBPARCELA
    CAST(SubParcela AS NVARCHAR(20)) AS SUBPARCELA,

    -- DESTINATARIO
    CAST(DescripcionPropietario AS NVARCHAR(250)) AS DESTINATARIO,

    -- CALLE Y ALTURA
    CAST(Calle AS NVARCHAR(250)) AS CALLE,
    CAST(Numero AS NVARCHAR(20)) AS ALTURA,

    -- PISO Y DEPARTAMENTO
    CAST(Piso AS NVARCHAR(20)) AS PISO,
    CAST(Departamento AS NVARCHAR(20)) AS DEPARTAMENTO,

    -- BARRIO
    CAST(Barrio AS NVARCHAR(250)) AS BARRIO,

    -- ENTRE_CALLES
    '' AS ENTRE_CALLE1,
    '' AS ENTRE_CALLE2,

    -- LOCALIDAD
    CAST(Localidad AS NVARCHAR(250)) AS LOCALIDAD,

    -- CODIGO_POSTAL Y CODIGO_POSTAL_ARGENTINA
    CAST(CodigoPostal AS NVARCHAR(20)) AS CODIGO_POSTAL,
    CAST(CodigoPostalNuevo AS NVARCHAR(20)) AS CODIGO_POSTAL_ARGENTINA,

    -- VIGENCIA (Ahora usando Efectivizado)
    Efectivizado AS VIGENCIA,

    -- SUPERFICIE Y CARACTERISTICA
    Superficie AS SUPERFICIE,
    CAST(Caracteristica AS NVARCHAR(20)) AS CARACTERISTICA,

    -- VALORES
    ValorTierra AS VALOR_TIERRA,
    Sued AS SUPERFICIE_EDIFICADA,
    ValorEdificado AS VALOR_EDIFICADO,
    ValorTierra1998 AS VALOR1998,
    ValorModificaciones AS VALOR_MEJORAS,
    ValorEdificado1997 AS EDIF1997,
    ValuacionFiscal AS VALOR_FISCAL,
    ValorModificaciones1997 AS MEJORAS1997,

    -- ORIGEN Y MOVIMIENTO
    CAST(PorcentajeOrigen AS NVARCHAR(250)) AS ORIGEN,
    CAST(CodigoMovimiento AS NVARCHAR(250)) AS MOTIVO_MOVIMIENTO,

    -- TITULAR
    CAST(Titular AS NVARCHAR(250)) AS TITULAR,
    CAST(CodigoTitular AS NVARCHAR(20)) AS CODIGO_TITULAR,

    -- DOMINIO
    CAST(PartidoOrigen AS NVARCHAR(250)) AS DOMINIO_ORIGEN,
    CAST(NumeroOriginal AS NVARCHAR(250)) AS DOMINIO_INSCRIPCION,
    CAST(TipoDominio AS NVARCHAR(250)) AS DOMINIO_TIPO,
    CAST(AñoSubdivision AS NVARCHAR(20)) AS DOMINIO_ANIO,
    CAST(UnidadFuncionalDominio AS NVARCHAR(50)) AS UNIDADES_FUNCIONALES,
    CAST(Serie AS NVARCHAR(50)) AS SERIE,

    -- RESPONSABLES
    '' AS CUIT_RESPONSABLE_1,
    '' AS NOMBRE_Y_APELLIDO_RESPONSABLE_1,
    '' AS TIPO_RESPONSABLE_1,
    '' AS CUIT_RESPONSABLE_2,
    '' AS NOMBRE_Y_APELLIDO_RESPONSABLE_2,
    '' AS TIPO_RESPONSABLE_2,

    -- CATASTRAL_CODIGO
    '' AS CATASTRAL_CODIGO

FROM dbo.Tripartito;
