from .lista import Lista
from .entidad import Entidad
from .entidad_definicion import EntidadDefinicion
from .persona_fisica import PersonaFisica
from .persona_juridica import PersonaJuridica
from .direccion import Direccion
from .contacto import Contacto
from .documento import Documento
from .archivo import Archivo
from .observacion import Observacion
from .etiqueta import Etiqueta
from .expediente import Expediente
from .medio_pago import MedioPago
from .cuenta_contable import CuentaContable
from .jurisdiccion import Jurisdiccion
from .pais import Pais
from .provincia import Provincia
from .localidad import Localidad
from .recurso_por_rubro import RecursoPorRubro
