USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE tipo_superficie
GO

INSERT INTO tipo_superficie
SELECT 
	cast(COD_TIPO_SUPERFICIE as bigint) id
	,COD_TIPO_SUPERFICIE codigo
	,DESCRIPCION nombre
	,ROW_NUMBER() OVER(ORDER BY COD_TIPO_SUPERFICIE) orden
	,CLASE
	,SUMA
	,0 adicionales
FROM MAJOR_CAMPANA.dbo.TIPO_SUPERFICIE
WHERE COD_TIPO_SUPERFICIE>0
ORDER BY id
GO
