USE LARAMIE_CAMPANA
GO

TRUNCATE TABLE jurisdiccion
GO

INSERT INTO jurisdiccion
SELECT 
	 ROW_NUMBER() OVER (ORDER BY EJERCICIO, AGRUPAMIENTO) id
	--,COD_JURISDICCION codigo
	,AGRUPAMIENTO codigo
	,NOMBRE
	,ROW_NUMBER() OVER (ORDER BY EJERCICIO, AGRUPAMIENTO) orden
	,EJERCICIO
	,AGRUPAMIENTO
	,MAJOR_CAMPANA.dbo.GET_FECHA(FECHA_BAJA) fecha_baja
	,NIVEL
	,TIPO
	,EJERCICIO_OFICINA
	,OFICINA
FROM MAJOR_CAMPANA.dbo.jurisdiccion
WHERE LEN(NOMBRE) > 0
ORDER BY EJERCICIO, AGRUPAMIENTO
GO
