USE LARAMIE_CAMPANA
GO

CREATE TABLE cuenta_corriente
(
    id                                    bigint NOT NULL,
    id_emision_ejecucion                  bigint,
    id_emision_cuenta_corriente_resultado bigint,
    id_cuenta                             bigint NOT NULL,
    id_tasa                               bigint NOT NULL,
    id_sub_tasa                           bigint NOT NULL,
    periodo                               varchar(20) NOT NULL,
    cuota                                 integer NOT NULL,
    codigo_delegacion                     varchar(50) NOT NULL,
    id_tipo_movimiento                    bigint NOT NULL,
    importe_debe                          numeric(18, 2) NOT NULL,
    importe_haber                         numeric(18, 2) NOT NULL,
    fecha_movimiento                      date NOT NULL,
    fecha_vencimiento1                    date NOT NULL,
    fecha_vencimiento2                    date NOT NULL,
    cantidad                              integer NOT NULL,
    id_edesur_cliente                     bigint,
    item                                  integer NOT NULL,
    id_certificado_apremio                bigint,
    numero_movimiento                     bigint NOT NULL,
    id_tipo_valor                         bigint NOT NULL,
    id_lugar_pago                         bigint,
    fecha_origen                          date NOT NULL,
    id_usuario_registro                   bigint NOT NULL,
    fecha_registro                        date NOT NULL,
    tasa_cabecera                         bit NOT NULL,
    id_plan_pago                          bigint,
    id_plan_pago_cuota                    bigint,
    detalle                               varchar(250) NOT NULL,
    numero_partida                        bigint NOT NULL,
    id_rubro                              bigint,
    fecha_vencimiento1_original           date NOT NULL,
    fecha_vencimiento2_original           date NOT NULL,
    fecha_vencimiento1_prorroga           date,
    fecha_vencimiento2_prorroga           date,
    id_usuario_proceso                    bigint,
    fecha_proceso                         date,
    fecha_cobro                           date
);