SELECT
	CC.NUMERO_CUENTA,
	CC.COD_TIPO_TRIBUTO,
	CC.COD_TASA,
	CC.COD_SUBTASA,
	CC.PERIODO,
	CC.CUOTA,
	CC.IMPORTE_DEBE,
	CC.IMPORTE_HABER,
	CC.FECHA_PROCESO,
	CC.DETALLE,
	CASE
		WHEN cta.id IS NULL THEN 'FALTA_CUENTA'
		WHEN st.id IS NULL THEN 'FALTA_SUBTASA'
		WHEN tm.id IS NULL THEN 'FALTA TIPO MOVIMIENTO'
		ELSE 'OK'
	END AS MOTIVO_EXCLUSION
FROM MAJOR_CAMPANA.dbo.CUENTA_CORRIENTE CC
	LEFT JOIN MAJOR_CAMPANA.dbo.LISTA L
		ON L.NOMBRE = 'TipoTributo' AND L.CODIGO = CC.COD_TIPO_TRIBUTO
	LEFT JOIN LARAMIE_CAMPANA.dbo.cuenta cta
		ON cta.numero_cuenta = CC.NUMERO_CUENTA AND cta.id_tipo_tributo = L.id
	LEFT JOIN LARAMIE_CAMPANA.dbo.tasa t
		ON t.codigo = CC.COD_TASA
	LEFT JOIN LARAMIE_CAMPANA.dbo.sub_tasa st
		ON st.codigo = CC.COD_SUBTASA AND st.id_tasa = t.id
WHERE cta.id IS NULL OR st.id IS NULL or tm.id IS NULL
