-- SELECT 
--        COD_CATEGORIA_UBICACION
--       ,NOMBRE
--       ,ORDEN
--       ,COEFICIENTE
-- FROM MAJOR.dbo.CATEGORIA_UBICACION


TRUNCATE TABLE LARAMIE.dbo.categoria_ubicacion
GO

INSERT INTO LARAMIE.dbo.categoria_ubicacion
SELECT 
     COD_CATEGORIA_UBICACION codigo
    ,NOMBRE nombre
    ,ROW_NUMBER() OVER (ORDER BY COD_CATEGORIA_UBICACION) orden
    ,COEFICIENTE coeficiente
FROM MAJOR.dbo.CATEGORIA_UBICACION
WHERE COD_CATEGORIA_UBICACION <> 0
GO