import express from 'express';

import ReporteRouter from './reporte-router';
import PagoRouter from './pago-router';
import ProcesoRouter from './proceso-router';
import ConfiguracionRouter from './configuracion-router';
import ListaRouter from './lista-router';
import EntidadRouter from './entidad-router';
import DireccionRouter from './direccion-router';
import InformacionAdicionalRouter from './informacion-adicional-router';
import ArchivoRouter from './archivo-router';
import ObservacionRouter from './observacion-router';
import EtiquetaRouter from './etiqueta-router';
import ContribuyenteRouter from './contribuyente-router';
import CuentaRouter from './cuenta-router';
import VariableRouter from './variable-router';
import VariableGlobalRouter from './variable-global-router';
import InmuebleRouter from './inmueble-router';
import CatastroRouter from './catastro-router';
import ComercioRouter from './comercio-router';
import VehiculoRouter from './vehiculo-router';
import CementerioRouter from './cementerio-router';
import FondeaderoRouter from './fondeadero-router';
import EspecialRouter from './especial-router';
import VinculoInmueble from './vinculo-inmueble-router';
import VinculoComercio from './vinculo-comercio-router';
import VinculoVehiculo from './vinculo-vehiculo-router';
import VinculoCementerio from './vinculo-cementerio-router';
import VinculoFondeadero from './vinculo-fondeadero-router';
import VinculoEspecial from './vinculo-especial-router';
import EmisionDefinicionRouter from './emision-definicion-router';
import EmisionEjecucionRouter from './emision-ejecucion-router';
import EmisionEjecucionCuentaRouter from './emision-ejecucion-cuenta-router';
import EmisionNumeracionRouter from './emision-numeracion-router';
import EmisionAprobacionRouter from './emision-aprobacion-router';
import ProcedimientoRouter from './procedimiento-router';
import TasaRouter from './tasa-router';
import SubTasaRouter from './sub-tasa-router';
import TasaVencimientoRouter from './tasa-vencimiento-router';
import CertificadoEscribanoRouter from './certificado-escribano-router';
import CertificadoApremioRouter from './certificado-apremio-router';
import CertificadoApremioItemRouter from './certificado-apremio-item-router';
import ApremioRouter from './apremio-router';
import PlantillaDocumentoRouter from './plantilla-documento-router';
import TipoActoProcesalRouter from './tipo-acto-procesal-router';
import OrganoJudicialRouter from './organo-judicial-router';
import TipoRelacionCertificadoApremioPersonaRouter from './tipo-relacion-certificado-apremio-persona-router';
import TipoMovimientoRouter from './tipo-movimiento-router';
import CuentaCorrienteItemRouter from './cuenta-corriente-item-router';
import CuotaPorcentajeRouter from './cuota-porcentaje-router';
import CuentaPagoRouter from './cuenta-pago-router';
import CuentaPagoItemRouter from './cuenta-pago-item-router';
import TipoControladorRouter from './tipo-controlador-router';
import ControladorRouter from './controlador-router';
import CuentaPruebaRouter from './cuenta-prueba-router';

import CuentaCorrienteCondicionEspecialRouter from './cuenta-corriente-condicion-especial-router';
import TipoPlanPagoRouter from './tipo-plan-pago-router';
import TipoVencimientoPlanPagoRouter from './tipo-vencimiento-plan-pago-router';
import PlanPagoDefinicionRouter from './plan-pago-definicion-router';
import PlanPagoRouter from './plan-pago-router';
import PlanPagoCuotaRouter from './plan-pago-cuota-router';
import PagoContadoDefinicionRouter from './pago-contado-definicion-router';
import PagoContadoRouter from './pago-contado-router';

import TipoVinculoCuentaRouter from './tipo-vinculo-cuenta-router';
import VinculoCuentaRouter from './vinculo-cuenta-router';

import ObraRouter from "./obra-router";
import TipoSuperficieRouter from "./tipo-superficie-router";
import GrupoSuperficieRouter from './grupo-superficie-router';
import TipoCondicionEspecialRouter from './tipo-condicion-especial-router';
import TipoInstrumentoRouter from './tipo-instrumento-router';
import RubroRouter from './rubro-router';
import TipoRecargoDescuentoRouter from './tipo-recargo-descuento-router';
import IncisoVehiculoRouter from './inciso-vehiculo-router';
import TipoVehiculoRouter from './tipo-vehiculo-router';
import CategoriaVehiculoRouter from './categoria-vehiculo-router';
import RubroLiquidacionRouter from './rubro-liquidacion-router';
import ZonaTarifariaRouter from './zona-tarifaria-router';
import GrupoRouter from './grupo-router';
import TipoConstruccionFunerariaRouter from './tipo-construccion-funeraria-router';
import TipoRubroComercioRouter from './tipo-rubro-comercio-router';
import RubroProvinciaRouter from './rubro-provincia-router';
import RubroBCRARouter from './rubro-bcra-router';
import MotivoBajaRubroComercioRouter from './motivo-baja-rubro-comercio-router';
import UbicacionComercioRouter from './ubicacion-comercio-router';
import CocheriaRouter from './cocheria-router';
import RegistroCivilRouter from './registro-civil-router';
import CategoriaTasaRouter from './categoria-tasa-router';
import TipoAnuncioRouter from './tipo-anuncio-router';
import CategoriaUbicacionRouter from './categoria-ubicacion-router';
import MotivoBajaComercioRouter from './motivo-baja-comercio-router';
import ObjetoCertificado from './objeto-certificado-router';
import EscribanoRouter from './escribano-router';
import TipoDDJJRouter from './tipo-ddjj-router';
import PaisRouter from './pais-router';
import ProvinciaRouter from './provincia-router';
import LocalidadRouter from './localidad-router';
import ConvenioParametroRouter from './convenio-parametro-router';

import DeclaracionJuradaComercioRouter from './declaracion-jurada-comercio-router';
import ClaseElementoRouter from './clase-elemento-router';
import TipoElementoRouter from './tipo-elemento-router';
import FiltroRouter from './filtro-router';
import ColeccionRouter from './coleccion-router';

import ReciboEspecialRouter from './recibo-especial-router';

const router = express.Router();

const getRoutes = () => {
    router.use('/api', ReporteRouter);
    router.use('/api', PagoRouter);
    router.use('/api', ProcesoRouter);
    router.use('/api', ConfiguracionRouter);
    router.use('/api', ListaRouter);
    router.use('/api', EntidadRouter);

    router.use('/api', DireccionRouter);
    router.use('/api', InformacionAdicionalRouter);
    router.use('/api', ArchivoRouter);
    router.use('/api', ObservacionRouter);
    router.use('/api', EtiquetaRouter);
    router.use('/api', ContribuyenteRouter);
    router.use('/api', CuentaRouter);
    router.use('/api', VariableRouter);
    router.use('/api', VariableGlobalRouter);
    router.use('/api', InmuebleRouter);
    router.use('/api', CatastroRouter);
    router.use('/api', ComercioRouter);
    router.use('/api', VehiculoRouter);
    router.use('/api', CementerioRouter);
    router.use('/api', FondeaderoRouter);
    router.use('/api', EspecialRouter);
    router.use('/api', VinculoInmueble);
    router.use('/api', VinculoComercio);
    router.use('/api', VinculoVehiculo);
    router.use('/api', VinculoCementerio);
    router.use('/api', VinculoFondeadero);
    router.use('/api', VinculoEspecial);
    router.use('/api', EmisionDefinicionRouter);
    router.use('/api', EmisionEjecucionRouter);
    router.use('/api', EmisionEjecucionCuentaRouter);
    router.use('/api', EmisionNumeracionRouter);
    router.use('/api', EmisionAprobacionRouter);
    router.use('/api', ProcedimientoRouter);
    router.use('/api', TasaRouter);
    router.use('/api', SubTasaRouter);
    router.use('/api', TasaVencimientoRouter);
    router.use('/api', CertificadoEscribanoRouter);
    router.use('/api', CertificadoApremioRouter);
    router.use('/api', CertificadoApremioItemRouter);
    router.use('/api', ApremioRouter);
    router.use('/api', PlantillaDocumentoRouter);
    router.use('/api', TipoActoProcesalRouter);
    router.use('/api', OrganoJudicialRouter);
    router.use('/api', TipoRelacionCertificadoApremioPersonaRouter);
    router.use('/api', CuentaCorrienteItemRouter);
    router.use('/api', CuotaPorcentajeRouter);
    router.use('/api', CuentaPagoRouter);
    router.use('/api', CuentaPagoItemRouter);
    router.use('/api', TipoControladorRouter);
    router.use('/api', ControladorRouter);
    router.use('/api', CuentaPruebaRouter);

    router.use('/api', TipoMovimientoRouter);
    router.use('/api', CuentaCorrienteCondicionEspecialRouter);
    router.use('/api', TipoPlanPagoRouter);
    router.use('/api', TipoVencimientoPlanPagoRouter);
    router.use('/api', PlanPagoDefinicionRouter);
    router.use('/api', PlanPagoRouter);
    router.use('/api', PlanPagoCuotaRouter);
    router.use('/api', PagoContadoDefinicionRouter);
    router.use('/api', PagoContadoRouter);

    router.use('/api', TipoVinculoCuentaRouter);
    router.use('/api', VinculoCuentaRouter);

    router.use('/api', ObraRouter);
    router.use('/api', TipoSuperficieRouter);
    router.use('/api', GrupoSuperficieRouter);
    router.use('/api', TipoCondicionEspecialRouter);
    router.use('/api', TipoInstrumentoRouter);
    router.use('/api', RubroRouter);
    router.use('/api', TipoRecargoDescuentoRouter);
    router.use('/api', IncisoVehiculoRouter);
    router.use('/api', TipoVehiculoRouter);
    router.use('/api', CategoriaVehiculoRouter);
    router.use('/api', RubroLiquidacionRouter);
    router.use('/api', ZonaTarifariaRouter);
	  router.use('/api', GrupoRouter);
    router.use('/api', TipoConstruccionFunerariaRouter);
    router.use('/api', TipoRubroComercioRouter);
    router.use('/api', RubroProvinciaRouter);
    router.use('/api', RubroBCRARouter);
    router.use('/api', MotivoBajaRubroComercioRouter);
    router.use('/api', UbicacionComercioRouter);
    router.use('/api', CocheriaRouter);
    router.use('/api', RegistroCivilRouter);
    router.use('/api', CategoriaTasaRouter);
    router.use('/api', TipoAnuncioRouter);
    router.use('/api', CategoriaUbicacionRouter);
    router.use('/api', MotivoBajaComercioRouter);
    router.use('/api', ObjetoCertificado);
    router.use('/api', EscribanoRouter);
    router.use('/api', TipoDDJJRouter);
    router.use('/api', PaisRouter);
    router.use('/api', ProvinciaRouter);
    router.use('/api', LocalidadRouter);
    router.use('/api', ConvenioParametroRouter);
    router.use('/api', DeclaracionJuradaComercioRouter);
    router.use('/api', ClaseElementoRouter);
    router.use('/api', TipoElementoRouter);
    router.use('/api', FiltroRouter);
    router.use('/api', ColeccionRouter);

    router.use('/api', ReciboEspecialRouter);
}

getRoutes();

export default router;