USE LARAMIE
GO

CREATE TABLE inhumado
(
    id bigint identity NOT NULL,
	numero_cuenta varchar(250) NOT NULL,
    id_cementerio bigint NOT NULL,
    id_tipo_documento bigint NOT NULL,
    numero_documento varchar(20) NOT NULL,
    apellido varchar(250) NOT NULL,
    nombre varchar(250) NOT NULL,
    fecha_nacimiento date,
    id_genero bigint NOT NULL,
    id_estado_civil bigint NULL,
    id_nacionalidad bigint NULL,
    fecha_defuncion date,
    fecha_ingreso date,
    id_motivo_fallecimiento bigint NOT NULL,
    numero_defuncion varchar(20) NOT NULL,
    libro varchar(20) NOT NULL,
    folio varchar(20) NOT NULL,
    id_registro_civil bigint NULL,
    acta varchar(20) NOT NULL,
    id_tipo_origen_inhumacion bigint NULL,
    observaciones_origen varchar(250) NOT NULL,
    id_tipo_condicion_especial bigint NULL,
    fecha_egreso date,
    fecha_traslado date,
    id_tipo_destino_inhumacion bigint NULL,
    observaciones_destino varchar(250) NOT NULL,
    fecha_exhumacion date,
    fecha_reduccion date,
    numero_reduccion varchar(20) NOT NULL,
    unidad varchar(250) NOT NULL,
    id_tipo_documento_responsable bigint NULL,
    numero_documento_responsable varchar(20) NOT NULL,
    apellido_responsable varchar(250) NOT NULL,
    nombre_responsable varchar(250) NOT NULL,
    fecha_hora_inicio_velatorio date,
    fecha_hora_fin_velatorio date,
    id_comercio_cocheria bigint,
    numero_cuit_cocheria varchar(20) NOT NULL,
	direccion varchar(1000) NOT NULL
)