SELECT id
    ,id_cementerio
    ,id_tipo_documento
    ,numero_documento
    ,apellido
    ,nombre
    ,fecha_nacimiento
    ,id_genero
    ,id_estado_civil
    ,id_nacionalidad
    ,fecha_defuncion
    ,fecha_ingreso
    ,id_motivo_fallecimiento
    ,numero_defuncion
    ,libro
    ,folio
    ,id_registro_civil
    ,acta
    ,id_tipo_origen_inhumacion
    ,observaciones_origen
    ,id_tipo_condicion_especial
    ,fecha_egreso
    ,fecha_traslado
    ,id_tipo_destino_inhumacion
    ,observaciones_destino
    ,fecha_exhumacion
    ,fecha_reduccion
    ,numero_reduccion
    ,unidad
    ,id_tipo_documento_responsable
    ,numero_documento_responsable
    ,apellido_responsable
    ,nombre_responsable
    ,fecha_hora_inicio_velatorio
    ,fecha_hora_fin_velatorio
    ,id_comercio_cocheria
    ,numero_cuit_cocheria
FROM LARAMIE.dbo.inhumado
ORDER BY id
