USE LARAMIE_CAMPANA
GO

CREATE TABLE cartel
(
    id bigint NOT NULL,
    id_comercio bigint NOT NULL,
    numero integer NOT NULL,
    id_tipo_anuncio bigint,
    id_tipo_cartel bigint,
    id_tipo_propiedad bigint,
    id_origen_declaracion_jurada bigint,
    id_categoria_ubicacion bigint,
    anuncio varchar(250) NOT NULL,
    marquesina integer NOT NULL,
    cantidad_publicidades integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_resolucion date,
    numero_ddjj varchar(20) NOT NULL,
    fecha_ddjj date,
    anio_ddjj varchar(20) NOT NULL,
    mes_ddjj integer NOT NULL,
    catastral_cir varchar(20) NOT NULL,
    catastral_sec varchar(20) NOT NULL,
    catastral_cod varchar(20) NOT NULL,
    catastral_chacra varchar(20) NOT NULL,
    catastral_lchacra varchar(20) NOT NULL,
    catastral_quinta varchar(20) NOT NULL,
    catastral_lquinta varchar(20) NOT NULL,
    catastral_frac varchar(20) NOT NULL,
    catastral_lfrac varchar(20) NOT NULL,
    catastral_manz varchar(20) NOT NULL,
    catastral_lmanz varchar(20) NOT NULL,
    catastral_parc varchar(20) NOT NULL,
    catastral_lparc varchar(20) NOT NULL,
    catastral_subparc varchar(20) NOT NULL,
    catastral_ufunc varchar(20) NOT NULL,
    catastral_ucomp varchar(20) NOT NULL,
    id_cuenta_inmueble bigint,
    id_tasa bigint,
    id_sub_tasa bigint,
    alto numeric(18,2) NOT NULL,
    ancho numeric(18,2) NOT NULL,
    id_motivo_baja_comercio bigint,
    fecha_baja date,
    id_bloqueo_emision bigint,
    id_tipo_producto_publicitado bigint NOT NULL,
    superficie numeric(18,2) NOT NULL,
	direccion varchar(250) NOT NULL
)
GO